pipeline:
  name: Harness CI Observability Demo
  identifier: harness_ci_observability_demo
  projectIdentifier: demopipelineobservability
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.githubpublicrepos
        repoName: harness-pipeline-failure-and-observability
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Demo
        identifier: demo
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.k8s_docker_desktop
              namespace: harness-delegate-ng
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Demo Script
                  identifier: run_demo_script
                  spec:
                    connectorRef: account.dockerhub_public
                    image: alpine:3.19
                    shell: Bash
                    command: |
                      chmod +x harness-ci-observability-demo/build.sh
                      ./harness-ci-observability-demo/build.sh
              - step:
                  type: Run
                  name: Soft Failure Expected
                  identifier: soft_failure_expected
                  spec:
                    connectorRef: account.dockerhub_public
                    image: alpine:3.19
                    shell: Bash
                    command: |
                      chmod +x harness-ci-observability-demo/soft-fail.sh
                      ./harness-ci-observability-demo/soft-fail.sh || true
              - step:
                  type: Run
                  name: Show Summary Artifact
                  identifier: show_summary_artifact
                  spec:
                    connectorRef: account.dockerhub_public
                    image: alpine:3.19
                    shell: Bash
                    command: |
                      cat artifacts/demo-summary.json
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
